version: '3'

services:
    node:
        container_name: auth-api-app
        build:
            context: .
            dockerfile: app.Dockerfile
        image: node:alpine
        command: "npm run dev"
        ports:
            - '${APP_PORT:-3000}:3000'
            - "9222:9222"
        volumes:
            - './:/usr/app'
        networks:
            - lan
        depends_on:
            - postgres
            - redis

    postgres:
        container_name: auth-api-db
        image: postgres:12-alpine
        user: postgres
        build:
            context: .
            dockerfile: db.Dockerfile
        image: auth/database
        environment:
            POSTGRES_USER: ${DB_USER:-postgres}
            POSTGRES_PASSWORD: ${DB_PASSWORD:-changeme}
            PGDATA: /data/postgres
        volumes:
            - postgres:/data/postgres
        ports:
            - '${DB_PORT:-5432}:5432'
        networks:
            - lan
        restart: unless-stopped

    redis:
        container_name: auth-api-redis
        image: redis
        command: redis-server --requirepass Redis!!@
        ports:
            - '${REDIS_DB_PORT:-6379}:6379'
        networks:
            - lan
        restart: unless-stopped

    pgadmin:
        container_name: auth-api-db-interface
        image: dpage/pgadmin4
        environment:
            POSTGRES_USER: ${DB_USER:-postgres}
            POSTGRES_PASSWORD: ${DB_PASSWORD:-changeme}
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@admin.com}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
        volumes:
            - pgadmin:/var/lib/pgadmin
        ports:
            - "${PGADMIN_PORT:-5050}:80"
        depends_on:
            - postgres
        networks:
            - lan
        restart: unless-stopped

networks:
    lan:
        driver: bridge

volumes:
    postgres:
    pgadmin:
