version: '3'

services:
    node:
        container_name: fertigation-auth-api-app
        build:
            context: .
            dockerfile: app.Dockerfile
        image: node:alpine
        command: "npm run dev"
        ports:
            - '${APP_PORT:-3000}:3000'
            - "9222:9222"
        volumes:
            - './:/usr/app'
        networks:
            - fertigation-network
        depends_on:
            - postgres
            - redis

    postgres:
        container_name: fertigation-auth-api-db
        # image: postgres:12-alpine
        user: postgres
        build:
            context: .
            dockerfile: db.Dockerfile
        image: auth/database
        environment:
            POSTGRES_USER: ${DB_USERNAME:-postgres}
            POSTGRES_PASSWORD: ${DB_PASSWORD:-changeme}
            PGDATA: /data/postgres
        volumes:
            - postgres:/data/postgres
        ports:
            - '${DB_PORT:-5432}:5432'
        networks:
            - fertigation-network
        restart: unless-stopped

    redis:
        container_name: fertigation-auth-api-redis
        image: redis
        command: redis-server --requirepass Redis!!@
        ports:
            - '${REDIS_DB_PORT:-6379}:6379'
        networks:
            - fertigation-network
        restart: unless-stopped

networks:
    fertigation-network:
        driver: bridge

volumes:
    postgres:
    pgadmin:
