# For more information: https://laravel.com/docs/sail
version: '3'
services:
  mailhog:
    container_name: fertigation-auth-api-mailhog
    image: 'mailhog/mailhog:latest'
    ports:
      - '${FORWARD_MAILHOG_PORT:-1025}:1025'
      - '${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025'
    networks:
      - fertigation-network

  pgadmin:
    container_name: fertigation-auth-api-db-interface
    image: dpage/pgadmin4
    environment:
        POSTGRES_USER: ${DB_USERNAME:-postgres}
        POSTGRES_PASSWORD: ${DB_PASSWORD:-changeme}
        PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@admin.com}
        PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
        - pgadmin:/var/lib/pgadmin
    ports:
        - "${PGADMIN_PORT:-5050}:80"
    depends_on:
        - postgres
    networks:
        - fertigation-network
    restart: unless-stopped
